<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-PaymentGateway.Worker-867ee133-6745-4872-9a81-737a4c06e6e5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.29" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.29" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />    
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PaymentGateway.Shared\PaymentGateway.Shared.csproj" />
    <ProjectReference Include="..\PaymentGateway.Domain\PaymentGateway.Domain.csproj" />
    <ProjectReference Include="..\PaymentGateway.Infrastructure\PaymentGateway.Infrastructure.csproj" />
  </ItemGroup>
</Project>
